### PR TITLE
organize and create real tasveer package

### PR DESCRIPTION
**Pull request by wvoliveira**
Hello.

I just organize your project with pylint and autopep8.

### CODE REVIEW

**Comment by AbhinavMir** [comment]
Hi, can you elaborate a bit more on the 'organize' part?

**Comment by wvoliveira** [comment]
I just kept the necessary files, the cleanest code and deleted some unnecessary files.

**Comment by AbhinavMir** [comment]
Please keep license.txt 
And could you let me know what simple.py does?

**Comment by wvoliveira** [comment]
What do you think about putting license.txt when you have a function that really differentiates with the google_images_download library? Because this google library does exactly what your package is willing to offer.

Just a suggestion, if you want me to leave the license, I leave. No problem.

The "simple.py" file uses the tasveer package to demonstrate how people can use it.

**Pull request closed without merging**
